# listening address
bind: "0.0.0.0:25565"
keepAliveTimeout: 30s

# rate limiter
filters:
  rateLimiter:
    # maximum number of requests allowed per time window
    requestLimit: 10
    # Duration of the time window (in seconds)
    windowLength: 1
    # block duration after limit exceeded (in seconds)
    blockDuration: 300

# proxy mode
proxyMode: "passthrough"

# connection timeout (in seconds)
options:
  connection_timeout: 60

# configrations
file_provider:
  proxies_path: ["/app/config/proxies"]
  file_type: "yaml"
  # disable hot reload
  # as its not needed now
  watch: false

# status cache
cache:
  status_ttl_seconds: 60
  max_status_entries: 100

# motd
motds:
  unknown:
    max_players: 64
    online_players: 0
    text: "§9joinst this servere now worme.§b§d§f§d§b"
    favicon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGYktHRAD/AP8A/6C9p5MAAAAHdElNRQfpBhUTFSOeqjioAAAMaUlEQVR42tVbXY8cRxU9t3p2djZO7NiyrVgoBHCiyJESJCQIT0jwmkciXgHxA/gV/AX4B4j3wAPiLbGRwHbkh/BCEAqO+PDHbrLx7uzOzvS9PFTVrVsf3TP2WjG0tJrp6p7uOueee2/VrVq6cOFlAQAihEO/+DPKz+31od+U99PY5ZFDBABk6GpxX93ur0nzt7F54ju3DnQL+DAqelLE1XPy9+Rgyv5IuCe2S9aXnEwCkSdh8vgWb4MbAq3tRFjDWw5UatD2HbVlKdwTrVsSEcnJSZicFnwLeGwjR/FV5eNGDwIBBAgEBFJCSjLaLuKBQa1OoyRM7ANPB977uoImqu+j9e5hrR8/PVgBif+MwGO/aiJIr7dIQCQV8AQMgd/U6kQUgKeAR0RNwBvFB+WLckIIgBAIAuGkiBJUjkEqEixJkxrg5uCJKAANwMm02ftpQBG1+SHhncKSdSmRIYAQ4GAUkQJeKza0SIjuMMn7Mgx+SO7W3/W7AU3pgeZZdVsEH1upI+/33vk1bSlINngyNbRdYoiEib1pUJFFZ51LVk/yt4owgTCSuc7/KYFXK0ZrE4ECCUpEZ4gIamAW4/tUBchWTJiU4Evrl5bPwAereyJcAZzU0umRNJ4JNLgFK1rg8ZkFEXBQNTgCuMcACWVgRCRgM/DR0gTvf865vN0Cd7n1m0QMMSDkwUbZBwzq77Ff0fpRDSFmuG49Cfb7ZAh8pVCX5K3gHcFpEDRAoxKKGKB8Grln8A1gf494ACb4eSK8yckFHlg86YGQdSTYeDAZBGys75zTwUkE75xLgDNXMFkhs34xJygZEDtstQMZE/hEABZE5MKeVIdNSCjx+TaTBWgQfHxLBj7I3DmTCl0OPFdBGuGhEVgtaKJESEpz/pmChIY6AjP77rkGCaEtI7FwhdG5gLXmEPiAtM4M5ejPDG5acYBU+pJGdyJBOWYE6PwtHFKfcw4MBnFOgvSi724Br2JAwwfUohrUXJJxAkzZdx8o/e+3ZzO88MI5dN1ECWFhHB58gcXiKHvd1nSG558/i85NNI8z93j0aB+L46MQ6Uml75z3BnCbBOccmFmzhEjtCsU4oJC++m36c5W103fn8jEAEeHq1Wt490c/w2y2o5yv+hV+99vf4MPb1/0gJxxXr17DD9/9KWazHe1kv1rhvfd+jds3PwB7FH5E6LwCVO0scETgIC6KEylHQO9f3FYB2gqI0ofN9Qb0MPjY5p9x/sIlvPbaNUynM30ps+DipZfgJh2EWd95/sIlvPpqfe+lS1dAzoEgYbDDIFCwdCCBgvc4+MAYxwYAhPIYkKtgYDZYSd+oIF5rWd7GAZ8lfIfZh+MAKgAgAlMeFJmlujfGHRGGhO8VCeHTPyiOmkJAjTJxgGhWKGaDtRvUQ1s9Rxz1UXbdZwsk4mhkWOGMsmJoNFWdvEN2Gh0GQs5BAglqdQopJJBlpxtCYQxBUqXDSVmzG7M+NO/nQJ1zcF2HruuUCOccJpOtJgtdN8HWdBvMvQbMbjIZvHc63UbfrwDxquj7HmzUBBJvYRAQswDHmCmh7z6/lrEgmw22p7qWmODjIKMG3/m3vvk2Xn/9zWxOcOXKV9F1XaWwN9/8Ns6dfdEEQcJLL73cvPett76Dc+fOe3cI2eGTTz7GrZsf4GRxrAMHHT/ENBoGQDq48gOLKhbQ5cvfSCHBOR/9nf+LOT/6vnMxBrgsBsx2nsOPf/JzfP8H76jfxqNdlW1Xilv31jPRDh/e/iN+9ctf4NEXn4PZD5SEOXyKaRMwM4RtO+u8QaSqCZqiBmrfjzeQi52JAyIH57qsODF+1L44eGdxo4h4Q5n5CPqkAt//UEM0tQltD+pQQptMxx8YUqCSj6M5c8NTKoM/zpHGHKkPqSvm3GIKXxJWSgRUFwtwaaZXTHXdxsXep8xAyljJFnld0hKDhjuhVEArICYeyDzUpESsSXlP/UjVYBuIs/dr34bJqwjIiEDGRFYrVFooJ+PL1QEZ17TVJiP7ghAYI5PB41qPF4xHqGzK+2wcwCAsjVMTglIllQIKCdW1/KKUVfrSMwmCMEUWyqxcdmmsd655QzOwGzYtH/SMguAoOlp3Q07Aqd6+YT7/3zvoaRDw/3+ckgB5xvo/Zd8jAdK61mjUwmVaw3j2LiCt08075RVgV2Dr01CgLBvs6ZfPgl8kSUvlCIsmkJKC8aTeLomNvRhJ+SLxyya/fFpHY0GhtEk0mNhJV3uiVhEQ+dIBjjJKxuUlLeMI0HOP5ckCfb/S6XCo5KPrThdmmBksorBFBMvlAn3fG6B6ManXgpWkYruuGPYIpQf7padURSWiVLKIFQeJdXvRwQIzY2/3IT69ezcsW/ljNtvBpcuXder6uIcIsLe7i8PDA21zzuHB/fvo+5WuFUbAYn4oGQdSP7itAM8gxfyelmWhM2nRujMIfoHSFzR7LI4Ps4LIkwK3/VkuT3B8dJg9s1+tQHDq/8LG/wvZ23OROmpnCiAh9Wkb6SmsxEocZqrvE4QE3Pc4OppjPj/Ilri6ra1TEgCcnCwwPzpMw3hymB8deBeIBjHASyIkBkxlwQbtoiIkSBuRtGZmKi2QtNpKEldgCKvlErduvY+PP/7I1/DDTPGNN76FV175OpybPrECPvrLLdz88/vetcSvLB082vf1QLOVpswGYuKCEUMVCCfF+yARaHAD3XoSKq4Sy9OaCQAWwd7efXz22YO0duAIly9fSbHkCVKlANjbe4B/3P0ruO/VkmJqfohtxVY6kfXyrwjwbpCXj6NbiAmCKRaGc7O5iShZZX54gIcPHmC6PUsrus7h7Nmz2Crco+977O/vo+97lTsz4+DgCy14QsqILirxmOZEclUMyz8QYDcXwWQDsKR9OGEjUlxyirEALICj4AopbsY4slqusLf7AFvTqQYU102ws7OD6XSadWa1WuGzvV2slgvN9SKM5eJELY7gdhAJn0hqEGt185lCQva+wZWhcRWEvrH4FZlYhke+REUEwJnaPNL8eWyjVFZ6y903AIUBX0ifcxI4uy4pYA65gK6gNFXAgLjUG7ORQeIurUACxQoDM+7d+ydu3PgDtqbb+tvnzjyPcy++gzNnzhjghMXiCHfu/An7n+/qYK9frfDpp39X/7cKEEOErgPYyM+F9TnFAKuE5lC4VgElqweQcendIzfzSg7MOMLuw3u4fv33ulwGABcvXsHb3/0eiL6iS7iegGPcuXMDd+/+TcnyC6tsZJ4CXQkeNihG8By21AyuV0gjCGYqiL7v5Wxlbj9BZoHSkUZfcgxhRq8+IFgczzE/PMTR0VwHTUQO8/kcR/M5licnoLh4oUHMjO4MYC6+l9JPE6ba940CpDmJiQQQ/BK3c84/LMwSYuCLSqBYHOI0RAaH+02JbbXqcf/efzDbPgOWpIDdh/ewXC6LwBXDPTJQ0RWa4BvSH/uniYlXupjIa1TAAnYCZ0lgvxJLVAe+uGSWFipTRtCNCojzh1WmAB0vcDGttREekoMaAM8D0l8zGxwigSFms4OLzk5+vT2SIADQC8SltX4Ja/IqDwIWi2P8+193sw4RAXt7D3E8nzesDj3XABiJGQGvcaIJ3uw9vnjxaxI7MbRjLNslmm2GqDdI6VPM3kFbu3euw87OGUyn26b0LFienGA+PwBzX8zhYVJe/b0CHzNE3476Zf3ApMHcFawSsk3JRUxIqQ+QPijHUdjC5YfOVgU9r3DwaB/rjjL4IbO6n7dY/1bLQ7KU1352FQSt9UeCIqdFSRbvDgLbHnJwJCKbN4ifZ4z8F1m2zd3M7LJRnOQjPw2MbNIj1ks/nk/KDqS9OnbbKul2k7g+T0xg4mDxpBayRIiYlRuEre8b7A0wvm9ndeXYvhwfjG/OqMGjFQRbJKgVTWCESwui0ov6fyIiyt6CzucdTZWVRJiULFlmCFYvXKH5HAyfT0xla1QJFlxkP1udZbM5MT4jxAC7TzimukHjI/l4+a9zZSBEoYgx8K3yWKgJxnRVSn8DEqJL2HXmSAQRYoEpAvJesL5ynIEoKj2l/EcVtAa8iQGPTwKKKXTKALmKIhk6JRROMaHqa95hGwT12kbANwOPMgY8DglriWiMLk1CW6OARocHJjTrrT4MHu2qcLlrk9KoiVLbOiLUj1v/MjvkBVI/czPQTwY+uEBpWUtCTURJzhgR8a3S6nQVebGBMh4H+HrwZmGkJmHITEkN7esb/+f4E60n0gBJrfZ15/74LwsByUwSz0vhAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI1LTA0LTAzVDEyOjUwOjEwKzAwOjAwxxvQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNS0wNC0wM1QxMjo1MDoxMCswMDowMLZGaH8AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjUtMDYtMjFUMTk6MjE6MzUrMDA6MDD3VhMxAAAAAElFTkSuQmCC"

# disable telementry
# as its not needed right now
telemetry:
  enabled: false
