name: minecraft-server-dev
services:
  minecraft-dev:
    image: itzg/minecraft-server:java24-graalvm
    container_name: minecraft-dev
    hostname: minecraft-dev
    restart: unless-stopped
    stop_grace_period: 1m
    tty: true
    stdin_open: true
    # memory limit + 2gb
    deploy:
      resources:
        limits:
          memory: 4g
    environment:
      EULA: true
      GUI: false
      # 1.21.(4/5) TBD
      # using 1.21.5 for now
      # TODO: version decision
      VERSION: 1.21.4
      # leaf server jar
      TYPE: custom
      CUSTOM_SERVER: /custom/leaf.jar
      # enable rolling logs
      # this should be default
      ENABLE_ROLLING_LOGS: true
      # disable rcon
      # why is this default
      ENABLE_RCON: false
      # memory limit
      MEMORY: 2G
      # flags for better performance
      USE_MEOWICE_FLAGS: true
      USE_MEOWICE_GRAALVM_FLAGS: true
      USE_SIMD_FLAGS: true
      # custom flags
      JVM_DD_OPTS: |
        paper.playerconnection.keepalive=60
        Paper.debugDynamicMissingKeys=false
        disable.watchdog=true
        Paper.skipServerPropertiesComments=true
        Paper.debugInvalidSkullProfiles=false
        paper.debug-sync-loads=false
        debug.entities=false
        Leaf.enableFMA=true
        convertLegacySigns=false
        Paper.skipServerPropertiesComments=true
        paper.disableGameRuleLimits=true
      # secrets
      REPLACE_ENV_VARIABLES: true
    env_file:
      # velocity forwarding secret
      - ../secrets/forwarding-secret.env
    networks:
      # network for velocity to minecraft communication
      - velocity-minecraft-dev
    volumes:
      # put stuff here by default
      # mostly cache
      - minecraft:/data/
      # logs
      - minecraft-logs:/data/logs
      # jar
      - ../../jar/leaf.jar:/custom/leaf.jar:ro
      # plugins
      - ../plugins/minecraft:/plugins
      # worlds
      - ../worlds/world:/data/world
      - ../worlds/nether:/data/world_nether
      - ../worlds/end:/data/world_the_end
      # datapacks
      - ../datapacks/:/data/world/datapacks
      # configs
      - ../config/minecraft/config:/data/config
      - ../config/minecraft/bukkit/bukkit.yml:/data/bukkit.yml
      - ../config/minecraft/bukkit/commands.yml:/data/commands.yml
      - ../config/minecraft/spigot/spigot.yml:/data/spigot.yml
      - ../config/minecraft/purpur/purpur.yml:/data/purpur.yml
      - ../config/minecraft/server/server.properties:/data/server.properties
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  minecraft:
  minecraft-logs:

networks:
  velocity-minecraft-dev:
    external: true
