name: minecraft-server-dev
services:
  velocity-dev:
    image: itzg/mc-proxy
    container_name: velocity-dev
    hostname: velocity-dev
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit + 512mb
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      # java port
      - 25565:25565
      # bedrock port
      - 19132:19132/udp
    networks:
      # network for velocity to minecraft communication
      - velocity-minecraft-dev
    environment:
      TYPE: VELOCITY
      # disable rcon
      # is this default here?
      ENABLE_RCON: false
      # TODO: update to .6 as soon as possible
      MINECRAFT_VERSION: 1.21.5
      # memory limit
      MEMORY: 512m
    volumes:
      # config
      - ../config/velocity/velocity.toml:/config/velocity.toml
      # plugins
      - ../plugins/velocity:/server/plugins
      # lang
      - ../config/velocity/lang:/server/lang
      # logs
      - velocity-logs:/server/logs
      # forwarding secret
      - ../secrets/forwarding.secret:/server/forwarding.secret
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  velocity-logs:

networks:
  velocity-minecraft-dev:
    external: true
