name: minecraft-server
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit
    deploy:
      resources:
        limits:
          memory: 1g
    secrets:
      - mariadb-password
    environment:
      # rootless
      PUID: 1000
      PGID: 1000
      # password
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/mariadb-password
    networks:
      # network for mariadb to minecraft & velocity communication
      - mariadb
    volumes:
      # data
      - mariadb:/config
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  mariadb:

networks:
  mariadb:
    external: true

secrets:
  mariadb-password:
    file: ../secrets/mariadb-password.txt
