name: minecraft-server
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit
    deploy:
      resources:
        limits:
          memory: 1g
    secrets:
      - mariadb-password
    environment:
      # rootless
      PUID: 1000
      PGID: 1000
      # password
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/mariadb-password
    networks:
      # network for mariadb to minecraft & velocity communication
      - mariadb
    volumes:
      # data
      - mariadb:/config
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    hostname: valkey
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit
    deploy:
      resources:
        limits:
          memory: 512mb
    secrets:
      - valkey-password
    # command needed to use password
    command: [
        "sh",
        "-c",
        '
        docker-entrypoint.sh
        --requirepass "$$(cat $$VALKEY_PASSWORD_FILE)"
        ',
      ]
    environment:
      VALKEY_PASSWORD_FILE: /run/secrets/valkey-password
    networks:
      # network for valkey to minecraft & velocity communication
      - valkey
    volumes:
      # data
      - valkey:/data
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

volumes:
  mariadb:
  valkey:

networks:
  mariadb:
  valkey:

secrets:
  mariadb-password:
    file: ../secrets/mariadb-password.txt
  valkey-password:
    file: ../secrets/valkey-password.txt
