name: minecraft-server
services:
  infrarust:
    image: shadowner/infrarust:latest
    container_name: infrarust
    hostname: infrarust
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit
    deploy:
      resources:
        limits:
          memory: 100mb
    ports:
      # port for java
      - 25565:25565
    networks:
      # network for infrarust to velocity communication
      - infrarust-velocity
    volumes:
      # config
      - ../config/infrarust/config.yml:/etc/infrarust/config.yaml
      - ../config/infrarust/proxies:/etc/infrarust/proxies
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  velocity:
    image: itzg/mc-proxy:latest
    container_name: velocity
    hostname: velocity
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit + 512mb
    deploy:
      resources:
        limits:
          memory: 1g
    secrets:
      - luckperms-database-password
    ports:
      # bedrock port
      - 19132:19132/udp
    networks:
      # network for infrarust to velocity communication
      - infrarust-velocity
      # network for velocity to minecraft communication
      - velocity-minecraft
      # network for broadcaster to velocity communication
      - broadcaster-velocity
      # networks for databases
      - mariadb
    environment:
      TYPE: VELOCITY
      # disable rcon
      # is this default here?
      ENABLE_RCON: false
      # TODO: update to .6 as soon as possible
      MINECRAFT_VERSION: 1.21.5
      # memory limit
      MEMORY: 512m
      # secrets
      CFG_LUCKPERMS_DATABASE_PASSWORD_FILE: /run/secrets/luckperms-database-password
    volumes:
      # server mount, only needed for it to stop creating random volumes
      - velocity-server:/server
      # config
      - ../config/velocity/velocity.toml:/config/velocity.toml
      # plugins
      - ../plugins/velocity:/server/plugins
      # lang
      - ../config/velocity/lang:/server/lang
      # logs
      - velocity-logs:/server/logs
      # forwarding secret
      - ../secrets/forwarding.secret:/server/forwarding.secret
      # geyser key
      - ../secrets/key.pem:/plugins/floodgate/key.pem
      - ../secrets/key.pem:/plugins/Geyser-Velocity/key.pem
      # geyser cache
      - geyser-cache:/data/plugins/Geyser-Velocity/cache
      - geyser-cache:/data/plugins/geyserextras/cache
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  velocity-server:
  velocity-logs:
  geyser-cache:
  geyser-extra-cache:

networks:
  infrarust-velocity:
  velocity-minecraft:
    external: true
  broadcaster-velocity:
    external: true
  mariadb:
    external: true

secrets:
  luckperms-database-password:
    file: ../secrets/luckperms-database-password.txt
