name: minecraft-server
services:
  router-minecraft:
    image: itzg/mc-router:latest
    container_name: router-minecraft
    hostname: router-minecraft
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      USE_PROXY_PROTOCOL: true
      MAPPING: |
        mc.friet.men=minecraft:25565
    ports:
      - 25565:25565
    networks:
      - router-velocity
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      minecraft:
        condition: service_healthy

  velocity:
    image: itzg/mc-proxy:latest
    container_name: velocity
    hostname: velocity
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit + 512mb
    deploy:
      resources:
        limits:
          memory: 1g
    secrets:
      - luckperms-database-password
    ports:
      # bedrock port
      - 19132:19132/udp
    networks:
      # network for mc-router to velocity communication
      - router-velocity
      # network for velocity to minecraft communication
      - velocity-minecraft
      # network for broadcaster to velocity communication
      - broadcaster-velocity
      # networks for databases
      - mariadb
    environment:
      TYPE: VELOCITY
      # disable rcon
      # is this default here?
      ENABLE_RCON: false
      # TODO: update to .6 as soon as possible
      MINECRAFT_VERSION: 1.21.5
      # memory limit
      MEMORY: 512m
      # secrets
      REPLACE_ENV_VARIABLES: true
      CFG_LUCKPERMS_DATABASE_PASSWORD_FILE: /run/secrets/luckperms-database-password
    volumes:
      # server mount, only needed for it to stop creating random volumes
      - velocity-server:/server
      # config
      - ../config/velocity/velocity.toml:/config/velocity.toml
      # plugins
      - ../plugins/velocity:/server/plugins
      # lang
      - ../config/velocity/lang:/server/lang
      # logs
      - velocity-logs:/server/logs
      # forwarding secret
      - ../secrets/forwarding.secret:/server/forwarding.secret
      # geyser key
      - ../secrets/key.pem:/plugins/floodgate/key.pem
      - ../secrets/key.pem:/plugins/Geyser-Velocity/key.pem
      # geyser cache
      - geyser-cache:/data/plugins/Geyser-Velocity/cache
      - geyser-cache:/data/plugins/geyserextras/cache
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  velocity-server:
  velocity-logs:
  geyser-cache:
  geyser-extra-cache:

networks:
  router-velocity:
  velocity-minecraft:
    external: true
  broadcaster-velocity:
    external: true
  mariadb:
    external: true

secrets:
  luckperms-database-password:
    file: ../secrets/luckperms-database-password.txt
