name: minecraft-server
services:
  infrarust:
    image: infrarust/infrarust:latest
    container_name: infrarust
    hostname: infrarust
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit
    deploy:
      resources:
        limits:
          memory: 100mb
    ports:
      # port for java
      - 25565:25565
    networks:
      # network for infrarust to velocity communication
      - infrarust-velocity
    volumes:
      # config
      - ../config/infrarust/config.yaml:/etc/infrarust/config.yaml
      - ../config/infrarust/proxies:/etc/infrarust/proxies
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  velocity:
    image: itzg/mc-proxy:latest
    container_name: velocity
    hostname: velocity
    restart: unless-stopped
    stop_grace_period: 1m
    # memory limit + 512mb
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      # bedrock port
      - 19132:19132/udp
    networks:
      # network for infrarust to velocity communication
      - infrarust-velocity
      # network for velocity to minecraft communication
      - velocity-minecraft
      # network for broadcaster to velocity communication
      - broadcaster-velocity
      # networks for databases
      - mariadb
      - valkey
    environment:
      TYPE: VELOCITY
      # disable rcon
      # is this default here?
      ENABLE_RCON: false
      # 1.21.(4/5) TBD
      # using 1.21.5 for now
      # TODO: version decision
      MINECRAFT_VERSION: 1.21.4
      # memory limit
      MEMORY: 512m
    volumes:
      # config
      - ../config/velocity/velocity.toml:/config/velocity.toml
      # plugins
      - ../plugins/velocity:/plugins
      # lang
      - ../config/velocity/lang:/server/lang
      # logs
      - velocity-logs:/server/logs
      # forwarding secret
      - ../secrets/forwarding.secret:/server/forwarding.secret:ro
      # geyser key
      - ../secrets/key.pem:/plugins/floodgate/key.pem:ro
      - ../secrets/key.pem:/plugins/Geyser-Velocity/key.pem:ro
      # geyser cache
      - geyser-cache:/data/plugins/Geyser-Velocity/cache
      - geyser-cache:/data/plugins/geyserextras/cache
      # timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  velocity-logs:
  geyser-cache:
  geyser-extra-cache:

networks:
  infrarust-velocity:
  velocity-minecraft:
    external: true
  broadcaster-velocity:
    external: true
  mariadb:
    external: true
  valkey:
    external: true
